version: "3"
services:
  brycecooldb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ../TestTicket/20240215.01.21.01.sql:/docker-entrypoint-initdb.d/a.sql
  bryceblazorapp:
    build: ..
    ports:
      - 8085:8080
    environment:
     - "Postgres=Server=brycecooldb;Database=postgres;Port=5432;User id=postgres;Password=postgres;"

  
    